let lessons = [
    {
        'id': 1,
        'subject': "Math",
        'location': "London",
        'price': 49,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 2,
        'subject': "English",
        'location': "London",
        'price': 30,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 3,
        'subject': "Physics",
        'location': "London",
        'price': 75,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 4,
        'subject': "Chemistry",
        'location': "London",
        'price': 60,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 5,
        'subject': "Biology",
        'location': "London",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
]